name: Op

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "kumarashwani66686@gmail.com"
  GitHubName: "sujeet1243" 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          chmod +x bgmi 
          pip install telebot aiohttp psutil pytz flask pymongo 
          python3 m.py
